# Site settings
title: APPDREW 
email: andrew.carvajal@me.com
url: appdrew.com
description: "iOS dev in NYC making the new FOX Sports app"
-skills: "Swift | SwiftUI | Objective-C"
meta_author: Carvajal Andrew

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: appdrew

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000 #2ecc71
  primary-rgb: "155,89,182" #"128,179,255" purple
  secondary: 29c5ff #29c5ff blue
  secondary-dark: 29c5ff #29c5ff

# Footer settings
footer:
  copyright: Andrew Carvajal
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/andrew-carvajal-09549538/
  - title: github
    url: http://github.com/andrewcar
  - title: facebook
    url: https://facebook.com/theycallmeandrew
  - title: instagram
    url: https://www.instagram.com/andrewsphone

# Postal address (add as many lines as necessary)
address:
  - line: New York,
  - line: New York
  - line: USA

# Credits content
credits: 'No animals were harmed in the making of this website.'

# Build settings
markdown: kramdown
permalink: pretty
