rd# Site settings
title: Andrew Carvajal
email: andrew@appdrew.com
url: appdrew.com
description: "iOS Dev in New York building in Swift and Objective-C"
skills: "Swift 3 | Mobile Development | Objective-C"
meta_author: Carvajal Andrew

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: appdrew

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9b59b6 #2ecc71
  primary-rgb: "155,89,182" #"128,179,255"
  secondary: f1c40f #FD6E8A
  secondary-dark: 8e44ad #A2122F

# Footer settings
footer:
  copyright: Andrew Carvajal
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/3d_print_me/
  - title: facebook
    url: https://facebook.com/theycallmeandrew
  - title: stack-overflow
    url: http://stackoverflow.com/users/3376577/andrewcar
  - title: github
    url: http://github.com/andrewcar

# Postal address (add as many lines as necessary)
address:
  - line: New York,
  - line: New York
  - line: USA

# Credits content
credits: 'No animals were harmed in the making of this website.'

# Build settings
markdown: kramdown
permalink: pretty
